#포트변경
server:
  port: 8080



#database config
spring:
  datasource:
    sql-script-encoding: utf-8
    initialization-mode: always
    platform: postgres
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://223.194.70.105:22822/dao
    username: admin
    password: wowsan808@!@#$
  profiles:
# 개발환경
    active: dev
# 배포환경
#     active: prod    


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true