#포트변경
server:
  port: 8080



#database config
spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      username: admin
      password: wowsan808@!@#$
      jdbc-url: jdbc:postgresql://223.194.70.105:22822/dao
  profiles:
# 개발환경
    active: prod
  sql:
    init:
      encoding: utf-8
      mode: always
      platform: postgres
# 배포환경
#     active: prod   


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true